const React={Fragment:({children})=>children,createElement(type,props,...children){props=props||{};if(typeof type==='function')return type({...props,children});const el=document.createElement(type);for(const [k,v] of Object.entries(props)){if(k==='children'||v==null)continue;if(k==='className')el.className=v;else if(k==='style')Object.assign(el.style,v);else if(k.startsWith('on'))el.addEventListener(k.slice(2).toLowerCase(),v);else el.setAttribute(k,v)};const add=x=>{if(Array.isArray(x))x.forEach(add);else if(x!=null&&x!==false)el.append(x.nodeType?x:document.createTextNode(String(x)))};children.forEach(add);return el}};
let hookValue=-1,renderApp;function useState(initial){if(hookValue===-1)hookValue=initial;return [hookValue,v=>{hookValue=typeof v==='function'?v(hookValue):v;renderApp()}]}
function createRoot(node){return{render(component){renderApp=()=>{node.replaceChildren(App())};renderApp()}}}
const iconPaths={Search:'M21 21l-4.3-4.3M19 11a8 8 0 1 1-16 0 8 8 0 0 1 16 0',ChevronDown:'m6 9 6 6 6-6',ChevronLeft:'m15 18-6-6 6-6',ChevronRight:'m9 18 6-6-6-6',ArrowRight:'M5 12h14m-6-6 6 6-6 6',Menu:'M4 6h16M4 12h16M4 18h16',MapPin:'M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Zm-8 3a3 3 0 1 0 0-6 3 3 0 0 0 0 6',Phone:'M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1 1 .4 2 .7 2.8a2 2 0 0 1-.5 2.1L8 9.9a16 16 0 0 0 6 6l1.3-1.3a2 2 0 0 1 2.1-.5c.9.3 1.8.6 2.8.7a2 2 0 0 1 1.8 2.1Z'};
function Icon({name,...p}){return <svg {...p} viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d={iconPaths[name]||'M12 2v20M2 12h20M5 5l14 14M19 5 5 19'}/></svg>};
const makeIcon=name=>props=><Icon name={name} {...props}/>;
const Menu=makeIcon('Menu'),Search=makeIcon('Search'),ChevronDown=makeIcon('ChevronDown'),ChevronLeft=makeIcon('ChevronLeft'),ChevronRight=makeIcon('ChevronRight'),ArrowRight=makeIcon('ArrowRight'),MapPin=makeIcon('MapPin'),Phone=makeIcon('Phone'),Mail=makeIcon('Mail'),Facebook=makeIcon('Facebook'),Instagram=makeIcon('Instagram'),Linkedin=makeIcon('Linkedin'),Youtube=makeIcon('Youtube'),Landmark=makeIcon('Landmark'),PiggyBank=makeIcon('PiggyBank'),CreditCard=makeIcon('CreditCard'),Smartphone=makeIcon('Smartphone'),BadgePercent=makeIcon('BadgePercent'),ShieldCheck=makeIcon('ShieldCheck'),Send=makeIcon('Send'),Clock3=makeIcon('Clock3');

const img = (id, w=900) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=82`;

function Header(){return <><div className="top"><span className="active">Personal Banking</span><span>Business Banking</span><span>Who We Are</span><div/><span>ATMs & Branches</span><span>Scam Awareness</span><span>News & Activities</span><span>Customer Care</span><b>MM</b><b className="lang">EN</b></div><header><a className="logo" href="#"><span>YOMA</span> BANK <i>◆</i></a><nav>{['Accounts','Cards','Loans','Digital Banking','Promotions','Other Services'].map(x=><a>{x}<ChevronDown/></a>)}</nav><button className="search"><Search/></button><button className="login">Login <ArrowRight/></button><button className="career">Careers</button><button className="men"><Menu/></button></header></>}

const Tile=({className='',src,title,tag})=><article className={'service '+className} style={{backgroundImage:`linear-gradient(0deg,rgba(6,5,10,.68),transparent 62%),url('${src}')`}}>{tag&&<em>{tag}</em>}<h3>{title}</h3><ArrowRight/></article>;

function App(){const [faq,setFaq]=useState(-1); const faqs=['How can I apply online/mobile banking?','How do I activate my mobile banking?','I forgot my password to login again for online/mobile banking. How should I do?','How do I transfer to my own account via online/mobile banking?','How do I send money to other Yoma Bank account via mobile banking?'];return <div><Header/><main>
  <section className="hero"><div className="swoosh"></div><div className="heroCopy"><span>NEW WAY TO BANK</span><h1>Banking at<br/>your fingertips.</h1><p>Save, pay and grow your money with a mobile experience made for everyday life.</p><button>Learn More <ArrowRight/></button></div><div className="phones"><div className="phone back"><span>yoma</span><div className="screen"></div></div><div className="phone front"><span>YOMA BANK</span><b>Welcome back</b><div className="balance">Available Balance<br/><strong>2,450,000 MMK</strong></div></div></div><div className="heroDots"><i></i><i></i><i></i></div></section>
  <div className="quick"><span className="quick-label">Quick Services</span>{[[PiggyBank,'Save'],[Landmark,'Loans'],[BadgePercent,'Promotions'],[Smartphone,'Digital Banking'],[Send,'Wave']].map(([I,t])=><a><I/><span>{t}</span></a>)}</div>
  <section className="wrap services"><Title first="Our Personal Banking Services" second="at a glance"/><div className="mosaic"><Tile className="big" src={img('photo-1563013544-824ae1b704d3')} title="The high interest account for you"/><Tile src={img('photo-1551836022-d5d88e9218df')} title="MMQR"/><Tile src={img('photo-1563986768609-322da13575f3')} title="Next App" tag="Bank Smarter"/><Tile src={img('photo-1521791055366-0d553872125f')} title="Remittance"/><Tile src={img('photo-1529156069898-49953e39b3ac')} title="Insurance"/></div></section>
  <section className="appPromo"><div><span className="pill">▣ &nbsp; Next App</span><h2>Simple, convenient<br/>mobile banking for you.</h2><p>Yoma Bank Next App puts your banking in one place. Pay bills, transfer funds, check balances—all with a few taps.</p><div className="stores"><b> App Store</b><b>▶ Google Play</b><b>AppGallery</b></div><a>Learn more about Next App <ArrowRight/></a></div><div className="promoPhone"><div className="speaker"></div><h5>Good morning!</h5><div className="pBalance">Your balance<br/><b>2,450,000 Ks</b></div><div className="apps">⌁　▦　◎<br/>Pay　Transfer　More</div></div><ul><li><ShieldCheck/><div><b>Make payments using QR codes</b><small>With Yoma Bank Next App's Scan to Pay and YPS features</small></div></li><li><Clock3/><div><b>Open Fixed Deposit Account</b><small>Open a fixed deposit account from your mobile, hassle free</small></div></li></ul></section>
  <section className="rates wrap"><div><h2>Counter Rates</h2><p>Last updated on<br/><b>28 September, 2026 | 10:00 am</b></p><a>See more rates <ArrowRight/></a></div>{[['🇺🇸','USD','3,650 MMK','3,670 MMK'],['🇪🇺','EUR','4,180 MMK','4,198 MMK'],['🇸🇬','SGD','2,834 MMK','2,875 MMK']].map(r=><div className="rate"><h4>{r[0]} {r[1]}</h4><small>Buy　　　　　　　　 Sell</small><p><b>{r[2]}</b>　 <b>{r[3]}</b></p></div>)}</section>
  <section className="cards"><Title first="Pay with Yoma Cards"/><p>Enjoy special privileges on payments and easy cash withdrawals with Yoma Bank's debit and credit cards.</p><button>View all of our cards</button><div className="cardStack"><div className="bankcard gold">YOMA BANK <b>Privilege</b><i>▣</i><strong>●</strong></div><div className="bankcard black">YOMA BANK <b>Platinum</b><i>▣</i></div><div className="bankcard wine">YOMA BANK <b>Preferred</b><i>▣</i></div></div></section>
  <section className="wrap news"><div className="sectionHead"><h2>News & Activities</h2><div><button><ChevronLeft/></button><button><ChevronRight/></button></div></div><div className="newsGrid">{[["photo-1521737711867-e3b97375f902",'Yoma Bank Participates as Main Sponsor of the MCCPMD Event'],["photo-1522071820081-009f0129c71c",'Yoma Bank Core Banking Transformation Program Invitation'],["photo-1486406146926-c627a92ad1ab",'Yoma Bank Industrial Visit for the Next Generation of Young Learners']].map((n,i)=><article><img src={img(n[0])}/><div><b>{n[1]}</b><small>{i?'7 September 2026':'18 September 2026'}　•　Events & Activities</small><a>Read more <ArrowRight/></a></div></article>)}</div></section>
  <section className="locator wrap"><div className="find"><h2>Locate Us</h2><p>Filters</p><div><button>ATMs</button><button>Branches</button><select><option>Select Township</option></select></div><button className="findBtn">Search</button><p className="counts"><b>179</b> ATMs　 <b>85</b> Branches</p></div><div className="map"><div className="roads"></div>{[16,25,31,38,46,52,59,66,72,79,84].map((x,i)=><MapPin className="pin" style={{left:x+'%',top:(20+(i*17)%64)+'%'}} fill="#d51031"/>) }<span>Yangon</span></div></section>
  <section className="wrap faq"><Title first="Need help?" second="Get answers in our FAQs"/><div className="support"><div style={{backgroundImage:`linear-gradient(90deg,rgba(0,0,0,.7),transparent),url('${img('photo-1551836022-d5d88e9218df')}')`}}><b>Customer Care</b><small>09 966 966 966</small><a>Get help <ArrowRight/></a></div><div style={{backgroundImage:`linear-gradient(90deg,rgba(0,0,0,.8),transparent),url('${img('photo-1563986768494-4dee2763ff3f')}')`}}><b>Scam Awareness</b><a>View More <ArrowRight/></a></div></div><div className="questions">{faqs.map((q,i)=><div onClick={()=>setFaq(faq===i?-1:i)}><button>{q}<ChevronDown className={faq===i?'flip':''}/></button>{faq===i&&<p>Visit your nearest Yoma Bank branch or contact our customer care team. We are always happy to help.</p>}</div>)}<a>Read all FAQs <ArrowRight/></a></div></section>
 </main><Footer/></div>}

function Title({first,second}){return <div className="title"><h2>{first}{second&&<><br/>{second}</>}</h2><i></i></div>}
function Footer(){return <footer><div className="ask"><div><h2>Ask us anything</h2><p>We are here to provide helpful information and recommendations tailored to your needs.</p><span><MapPin/> Search Branches & ATM Locations　　<Phone/> (+95) 01 9662 9662</span></div><button>Contact us</button></div><div className="foot"><div><h4>Personal Banking</h4><a>Accounts & Deposits</a><a>Loans</a><a>Cards</a><a>Remittance</a><a>Digital Banking</a></div><div><h4>Business Banking</h4><a>Accounts</a><a>Loans</a><a>Trade Finance</a><a>Digital Banking</a><a>Get in Touch</a></div><div><h4>About Us</h4><a>About Yoma</a><a>Governance</a><a>Careers</a><a>News & Activities</a><h4>Follow Us</h4><p className="social"><Facebook/><Instagram/><Linkedin/><Youtube/></p></div><div><h4>Digital Login</h4><a>Business Portal</a><a>Payroll Portal</a><a>Supply Chain Financing</a></div><div><h4>Recent Blogs</h4><div className="blog">Smart ways to manage your money</div><div className="blog">Making banking easier every day</div></div></div><div className="copy"><span>Terms & Conditions　 Privacy Statement</span><span>© 2026 Copyright Yoma Bank. All rights reserved.</span><span>🇲🇲 MM　 🇬🇧 EN</span></div></footer>}

createRoot(document.getElementById('root')).render(<App/>);
